
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS "public";

ALTER SCHEMA "public" OWNER TO "pg_database_owner";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."address" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "phone" "text" NOT NULL,
    "address" "text" NOT NULL,
    "city" "text" NOT NULL,
    "state" "text" NOT NULL,
    "pincode" "text" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "preferred" boolean
);

-- ALTER TABLE "public"."address" OWNER TO "supabase_admin";

ALTER TABLE "public"."address" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."address_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."cart_product" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "variant_id" bigint NOT NULL,
    "qty" smallint NOT NULL,
    "checkout_id" bigint NOT NULL
);

-- ALTER TABLE "public"."cart_product" OWNER TO "supabase_admin";

ALTER TABLE "public"."cart_product" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cart_product_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."checkout" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "address_id" bigint,
    "shipping_mode" smallint DEFAULT '1'::smallint,
    "coupon_id" bigint
);

-- ALTER TABLE "public"."checkout" OWNER TO "supabase_admin";

ALTER TABLE "public"."checkout" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."checkout_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."coupon" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "coupon" "text" NOT NULL,
    "value" real NOT NULL,
    "value_type" smallint DEFAULT '1'::smallint NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "max_use" smallint,
    "checkout_visible" boolean DEFAULT false,
    "min_cart_value" real,
    "max_discount" real
);

-- ALTER TABLE "public"."coupon" OWNER TO "supabase_admin";

ALTER TABLE "public"."coupon" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."coupon_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."order" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "coupon_id" bigint,
    "discount" real,
    "coupon" "text",
    "shipping_mode" smallint,
    "shipping_cost" real,
    "address_id" bigint,
    "name" "text" NOT NULL,
    "mobile" "text" NOT NULL,
    "address" "text" NOT NULL,
    "city" "text" NOT NULL,
    "state" "text" NOT NULL,
    "pincode" "text" NOT NULL,
    "user_id" "uuid" NOT NULL
);

-- ALTER TABLE "public"."order" OWNER TO "supabase_admin";

ALTER TABLE "public"."order" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."order_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."order_product" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "product_id" bigint,
    "variant_id" bigint,
    "order_id" bigint NOT NULL,
    "product_title" "text" NOT NULL,
    "variant_title" "text" NOT NULL,
    "weight" real NOT NULL,
    "qty" smallint NOT NULL,
    "price" real NOT NULL
);

-- ALTER TABLE "public"."order_product" OWNER TO "supabase_admin";

ALTER TABLE "public"."order_product" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."order_product_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."product" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "slug" "text" NOT NULL,
    "image" "text",
    "description" "text",
    "variant_seq" "json",
    "category_id" bigint
);

ALTER TABLE "public"."product" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."product_category" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL
);

-- ALTER TABLE "public"."product_category" OWNER TO "supabase_admin";

ALTER TABLE "public"."product_category" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."product_category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."product" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."product_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."product_variant" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "product_id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "price" real NOT NULL,
    "compare_price" real,
    "included_shipping_cost" real,
    "image" "text",
    "weight" real NOT NULL,
    "slug" "text" NOT NULL
);

ALTER TABLE "public"."product_variant" OWNER TO "postgres";

ALTER TABLE "public"."product_variant" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."product_variant_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tokens" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "secret" "text" NOT NULL
);

-- ALTER TABLE "public"."tokens" OWNER TO "supabase_admin";

ALTER TABLE "public"."tokens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tokens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."address"
    ADD CONSTRAINT "address_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."cart_product"
    ADD CONSTRAINT "cart_product_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."checkout"
    ADD CONSTRAINT "checkout_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."checkout"
    ADD CONSTRAINT "checkout_user_id_key" UNIQUE ("user_id");

ALTER TABLE ONLY "public"."coupon"
    ADD CONSTRAINT "coupon_coupon_key" UNIQUE ("coupon");

ALTER TABLE ONLY "public"."coupon"
    ADD CONSTRAINT "coupon_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."order"
    ADD CONSTRAINT "order_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."order_product"
    ADD CONSTRAINT "order_product_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."product_category"
    ADD CONSTRAINT "product_category_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."product"
    ADD CONSTRAINT "product_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."product"
    ADD CONSTRAINT "product_slug_key" UNIQUE ("slug");

ALTER TABLE ONLY "public"."product_variant"
    ADD CONSTRAINT "product_variant_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tokens"
    ADD CONSTRAINT "tokens_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."tokens"
    ADD CONSTRAINT "tokens_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."address"
    ADD CONSTRAINT "address_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."cart_product"
    ADD CONSTRAINT "cart_product_checkout_id_fkey" FOREIGN KEY ("checkout_id") REFERENCES "public"."checkout"("id");

ALTER TABLE ONLY "public"."cart_product"
    ADD CONSTRAINT "cart_product_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variant"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."checkout"
    ADD CONSTRAINT "checkout_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."address"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."checkout"
    ADD CONSTRAINT "checkout_coupon_id_fkey" FOREIGN KEY ("coupon_id") REFERENCES "public"."coupon"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."checkout"
    ADD CONSTRAINT "checkout_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."order"
    ADD CONSTRAINT "order_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."address"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."order"
    ADD CONSTRAINT "order_coupon_id_fkey" FOREIGN KEY ("coupon_id") REFERENCES "public"."coupon"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."order_product"
    ADD CONSTRAINT "order_product_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."order"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."order_product"
    ADD CONSTRAINT "order_product_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."order_product"
    ADD CONSTRAINT "order_product_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variant"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."order"
    ADD CONSTRAINT "order_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."product"
    ADD CONSTRAINT "product_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."product_category"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."product_variant"
    ADD CONSTRAINT "product_variant_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id");

CREATE POLICY "Admin access" ON "public"."coupon" USING ((("auth"."jwt"() ->> 'email'::"text") = 'raghavvnarang@gmail.com'::"text")) WITH CHECK ((("auth"."jwt"() ->> 'email'::"text") = 'raghavvnarang@gmail.com'::"text"));

CREATE POLICY "Admin access" ON "public"."product" USING ((("auth"."jwt"() ->> 'email'::"text") = 'raghavvnarang@gmail.com'::"text")) WITH CHECK ((("auth"."jwt"() ->> 'email'::"text") = 'raghavvnarang@gmail.com'::"text"));

CREATE POLICY "Admin access" ON "public"."product_category" USING ((("auth"."jwt"() ->> 'email'::"text") = 'raghavvnarang@gmail.com'::"text")) WITH CHECK ((("auth"."jwt"() ->> 'email'::"text") = 'raghavvnarang@gmail.com'::"text"));

CREATE POLICY "Admin access" ON "public"."product_variant" USING ((("auth"."jwt"() ->> 'email'::"text") = 'raghavvnarang@gmail.com'::"text")) WITH CHECK ((("auth"."jwt"() ->> 'email'::"text") = 'raghavvnarang@gmail.com'::"text"));

CREATE POLICY "Enable all actions for users based on their own checkout_id" ON "public"."cart_product" USING ((EXISTS ( SELECT 1
   FROM "public"."checkout"
  WHERE ("checkout"."id" = "cart_product"."checkout_id")))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."checkout"
  WHERE ("checkout"."id" = "cart_product"."checkout_id"))));

CREATE POLICY "Enable all actions for users based on user_id" ON "public"."checkout" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."address" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable read access for all users" ON "public"."product_category" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."product_variant" FOR SELECT USING (true);

CREATE POLICY "Enable select for all" ON "public"."product" FOR SELECT USING (true);

CREATE POLICY "Enable select for authenticated users only" ON "public"."coupon" FOR SELECT TO "authenticated" USING (("is_active" = true));

ALTER TABLE "public"."address" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."cart_product" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."checkout" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."coupon" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."order" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."order_product" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."product" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."product_category" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."product_variant" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tokens" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."address" TO "postgres";
GRANT ALL ON TABLE "public"."address" TO "anon";
GRANT ALL ON TABLE "public"."address" TO "authenticated";
GRANT ALL ON TABLE "public"."address" TO "service_role";

GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."cart_product" TO "postgres";
GRANT ALL ON TABLE "public"."cart_product" TO "anon";
GRANT ALL ON TABLE "public"."cart_product" TO "authenticated";
GRANT ALL ON TABLE "public"."cart_product" TO "service_role";

GRANT ALL ON SEQUENCE "public"."cart_product_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."cart_product_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cart_product_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cart_product_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."checkout" TO "postgres";
GRANT ALL ON TABLE "public"."checkout" TO "anon";
GRANT ALL ON TABLE "public"."checkout" TO "authenticated";
GRANT ALL ON TABLE "public"."checkout" TO "service_role";

GRANT ALL ON SEQUENCE "public"."checkout_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."checkout_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."checkout_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."checkout_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."coupon" TO "postgres";
GRANT ALL ON TABLE "public"."coupon" TO "anon";
GRANT ALL ON TABLE "public"."coupon" TO "authenticated";
GRANT ALL ON TABLE "public"."coupon" TO "service_role";

GRANT ALL ON SEQUENCE "public"."coupon_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."coupon_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."coupon_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."coupon_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."order" TO "postgres";
GRANT ALL ON TABLE "public"."order" TO "anon";
GRANT ALL ON TABLE "public"."order" TO "authenticated";
GRANT ALL ON TABLE "public"."order" TO "service_role";

GRANT ALL ON SEQUENCE "public"."order_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."order_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."order_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."order_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."order_product" TO "postgres";
GRANT ALL ON TABLE "public"."order_product" TO "anon";
GRANT ALL ON TABLE "public"."order_product" TO "authenticated";
GRANT ALL ON TABLE "public"."order_product" TO "service_role";

GRANT ALL ON SEQUENCE "public"."order_product_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."order_product_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."order_product_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."order_product_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."product" TO "anon";
GRANT ALL ON TABLE "public"."product" TO "authenticated";
GRANT ALL ON TABLE "public"."product" TO "service_role";

GRANT ALL ON TABLE "public"."product_category" TO "postgres";
GRANT ALL ON TABLE "public"."product_category" TO "anon";
GRANT ALL ON TABLE "public"."product_category" TO "authenticated";
GRANT ALL ON TABLE "public"."product_category" TO "service_role";

GRANT ALL ON SEQUENCE "public"."product_category_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."product_category_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."product_category_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."product_category_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."product_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."product_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."product_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."product_variant" TO "anon";
GRANT ALL ON TABLE "public"."product_variant" TO "authenticated";
GRANT ALL ON TABLE "public"."product_variant" TO "service_role";

GRANT ALL ON SEQUENCE "public"."product_variant_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."product_variant_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."product_variant_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tokens" TO "postgres";
GRANT ALL ON TABLE "public"."tokens" TO "anon";
GRANT ALL ON TABLE "public"."tokens" TO "authenticated";
GRANT ALL ON TABLE "public"."tokens" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tokens_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
