version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - DATABASE_URI=${DATABASE_URI}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NEXT_PUBLIC_RAZORPAY_KEY_ID=${NEXT_PUBLIC_RAZORPAY_KEY_ID}
      - NEXT_PUBLIC_VERCEL_URL=${NEXT_PUBLIC_VERCEL_URL}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - NEXT_ADMIN_EMAIL=${NEXT_ADMIN_EMAIL}
    networks:
      - coolify

volumes:
  coolify:
    name: coolify
    external: true
